[project]
name = "sample-db"
version = "0.1.0"
authors = ["<Taha Dostifam> mr.tahadostifam@gmail.com"]

[dependencies]
libraries = []
library_path = []

[compiler]
cpu = "generic"
optimize = "o1"
sources = ["src/*"]
version = "0.0.1"
build_dir = "./build"
